spring:
  config:
    activate:
      on-profile: elementary

academy:
  division: ELEMENTARY
  min-attendance: 80

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [ðŸ‘¶ ì´ˆë“±ë¶€] [%thread] %-5level %logger{36} - %msg%n"
